[package]
name = "rply-codec"
version = "0.1.0"
edition = "2024"

[dependencies]
byteorder = "1.5.0"
flate2 = { version = "1.1.5", features = ["zlib-rs"] }
rmp = "0.8.14"
thiserror = "2.0.17"
zstd = "0.13.3"
